//
//  CardDetailsModels.swift
//  Cards
//
//  Created by irina on 21.05.2020.
//  Copyright (c) 2020 irina. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CardDetails
{
    struct DisplayedCard
    {
        var type: String
        var cardNumber: String
    }
  // MARK: Use cases
  
  enum SelectedCard
  {
    struct Request
    {
       
    }
    struct Response
    {
      var card: Card
    }
    struct ViewModel
    {
       var card: DisplayedCard
    }
  }
}
