//
//  CardDetailsInteractor.swift
//  Cards
//
//  Created by irina on 21.05.2020.
//  Copyright (c) 2020 irina. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CardDetailsBusinessLogic
{
  var card: Card? { get set }
    func fetchCard(card: CardDetails.SelectedCard.Request)
}

protocol CardDetailsDataStore
{
  var card: Card? { get set }
}

class CardDetailsInteractor: CardDetailsBusinessLogic, CardDetailsDataStore
{
  var presenter: CardDetailsPresentationLogic?
  //var worker: CardDetailsWorker?
  var card: Card?
  
  // MARK: fetch card
  
    func fetchCard(card: CardDetails.SelectedCard.Request)
  {
//    worker = CardDetailsWorker()
//    worker?.doSomeWork()
    guard let selectedCard = self.card else{ return }
    let response = CardDetails.SelectedCard.Response(card: selectedCard)
    presenter?.presentCard(response: response)
     
  }

}
