//
//  CardDetailsRouter.swift
//  Cards
//
//  Created by irina on 21.05.2020.
//  Copyright (c) 2020 irina. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CardDetailsRoutingLogic
{
 // func routeToCardList(segue: UIStoryboardSegue?)
}

protocol CardDetailsDataPassing
{
  var dataStore: CardDetailsDataStore? { get }
}

class CardDetailsRouter: NSObject, CardDetailsRoutingLogic, CardDetailsDataPassing
{
  weak var viewController: CardDetailsViewController?
  var dataStore: CardDetailsDataStore?
  
  // MARK: Routing
  
//  func routeToCardList(segue: UIStoryboardSegue?)
//  {
//    if let segue = segue {
//      let destinationVC = segue.destination as! CardListViewController
//      var destinationDS = destinationVC.router!.dataStore!
//      passDataToCardList(source: dataStore!, destination: &destinationDS)
//    } else {
//      let storyboard = UIStoryboard(name: "Main", bundle: nil)
//      let destinationVC = storyboard.instantiateViewController(withIdentifier: "CardListViewController") as! CardListViewController
//      var destinationDS = destinationVC.router!.dataStore!
//      passDataToCardList(source: dataStore!, destination: &destinationDS)
//      navigateToCardList(source: viewController!, destination: destinationVC)
//    }
//  }
//
//  // MARK: Navigation
//
//  func navigateToCardList(source: CardDetailsViewController, destination: CardListViewController)
//  {
//    source.show(destination, sender: nil)
//  }
//
  // MARK: Passing data
  
//  func passDataToCardList(source: CardDetailsDataStore, destination: inout CardListDataStore)
//  {
//    //destination.selectedCard = source.card
//
 // }
}
