//
//  CardListModels.swift
//  Cards
//
//  Created by irina on 21.05.2020.
//  Copyright (c) 2020 irina. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CardList
{
    struct DisplayedCard
    {
        var type: String
        var cardNumber: String
    }
    
    // MARK: Use cases
    
    enum FetchCards
    {
      struct Request
      {
      }
      struct Response
      {
        var cards: [Card]
      }
      struct ViewModel
      {
        var displayedCards: [DisplayedCard]
      }
    }
    
    enum CreateCard
    {
      struct Request
      {
        var created: Double
        var type: String
        var cardNumber: String
      }
      struct Response
      {
        var cards: [Card]
      }
      struct ViewModel
      {
         var displayedCards: [DisplayedCard]
      }
    }
    
    enum SelectedCard
    {
      struct Request
      {
        var card: DisplayedCard
      }
      struct Response
      {
        var card: DisplayedCard
      }
      struct ViewModel
      {
         var card: DisplayedCard
      }
    }
    
}

