//
//  CardListWorker.swift
//  Cards
//
//  Created by irina on 21.05.2020.
//  Copyright (c) 2020 irina. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class CardListWorker
{
 
  func fetchCards(completionHandler: @escaping (() throws -> [Card]) -> Void) {
    
    CoreDataStore.fetchList(CoreDataCard.self, completionHandler: { (coreDataCards: () throws -> [CoreDataCard]) in
      do {
        let coreDataCards = try coreDataCards()
        let cards = coreDataCards.map { $0.toCard() }
        completionHandler { return cards}
      } catch {}
    })
  }
  
  func fetchCard(number: String, completionHandler: @escaping (() throws -> Card?) -> Void)
  {
    CoreDataStore.fetchItem(CoreDataCard.self, number: number, completionHandler: { (coreDataCard: () throws -> CoreDataCard?) in
        do {
            let coreDataCard = try coreDataCard()
            if let card = coreDataCard?.toCard() {
                completionHandler { return card }
            } else {
                throw CoreDataStoreError.CannotFetch("Cannot fetch item \(number)")
            }
        } catch {
          //  print(error)
        }
    })
 
  }
  
    func createCard(cardToCreate: Card, completionHandler: @escaping (Card?) -> Void) {
        
        let newCard = CoreDataCard(context: CoreDataStore.context)
        newCard.type = cardToCreate.type
        newCard.created = cardToCreate.created
        newCard.cardNumber = cardToCreate.cardNumber
        
        CoreDataStore.saveContext { (succes: Bool) in
            if succes {
               completionHandler (cardToCreate)
            }
        }
    }
   
}


 
